# 数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 19980905
    url: jdbc:mysql://localhost:3306/djmall?characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&useSSL=false
  data:
    solr:
      host: http://localhost:8085/solr/SolrCore
  rabbitmq:
    host: 192.168.221.210
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
    connection-timeout: 60000

# Dubbo
dubbo:
  application:
    name: task # 应用名
    qos-enable: false # 关闭在线调试
  registry:
    address: zookeeper://localhost:2181 # 注册中心地址
  protocol:
    name: dubbo # 协议名
    port: 20884 # 服务端口
  consumer:
    check: false
    timeout: 60000
  provider:
    timeout: 60000
#日志
logging:
  level:
    com.dj.mall.auth.mapper: debug