# 数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 19980905
    url: jdbc:mysql://localhost:3306/djmall?characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&useSSL=false
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss #前台传给后台时间转换

# Mybatis-plus
mybatis-plus:
  type-aliases-package: com.dj.mall.dict.entity # 类别名
  mapper-locations: classpath:/mapper/**/*.xml # mapper文件
  configuration:
    map-underscore-to-camel-case: true # 驼峰映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# Dubbo
dubbo:
  application:
    name: dict-provider # 应用名
    qos-enable: false # 关闭在线调试
  registry:
    address: zookeeper://localhost:2181 # 注册中心地址
  protocol:
    name: dubbo # 协议名
    port: 20881 # 服务端口
  consumer:
    check: false
    timeout: 60000
  provider:
    timeout: 60000
#日志
logging:
  level:
    com.dj.mall.auth.mapper: debug